
baseurl: "/example" # the subpath of your site, e.g. /blog/
url: "http://jekyll.github.io" # the base hostname & protocol for your site
collections:
  authors:
    output: true
    

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

      
 
